#! /bin/zsh

############################################################################
#                                   Fernandez Garay Jorge - 08/2004
# depu_nov_LN
#
# Es disparado por el JOB DEPU_LN_NOV, de la cadena CARGA_NOV_LN, que corre en
# sucursales, para realizar la Carga de Noved. de Lista Negra
# Ejecuta el programa depu_LN_nov, que depura los archivos de Noved. de 
# Lista Negra, manteniendo en linea solo los ultimos 7.
#
############################################################################

set -x

if [ "$#" -ne 0 ]
then
         echo "\n\n`date +"%d/%m/%Y"` $0: Error en la cantidad de parametros recibida"

         exit 32
fi

EXIT_STAT=''
export EXIT_STAT

if [ -f /tecnol/carga_LN/depu_LN_nov -a -x /tecnol/carga_LN/depu_LN_nov ]
then
         /tecnol/carga_LN/depu_LN_nov
         EXIT_STAT="$?"

         if [ "$EXIT_STAT" -ne 0 ]
         then
                  echo "\n\n$0: LOs errores de cancelacion del prog. depu_LN_nov, hay que"
                  echo "buscarlos en el sysout de ejecucion del Job DEPU_LN_NOV"
         fi

else
         echo "\n\n`date +"%d/%m/%Y"` $0: Este programa no existe o no posee permiso de ejecucion"
         exit 31
fi

exit "$EXIT_STAT"
