#! /bin/ksh

############################################################################
#                                   Fernandez Garay Jorge - 08/2004
# launch_actulistaneg
#
# Lanzado por el Job ACTU_NOVLN, de la cadena CARGA_NOV_LN de Control-M,
# que corre en sucursales para realizar la Carga de Novedades de Lista Negra.
# Ejecuta el programa actulistaneg.sh, que ejecuta el procedimiento SQL que
# actualiza Las Noved. de Lista Negra ide la fecha, transmitidas desde eli
# SP9, en las tables de StoreFlow
#
############################################################################

set -x

if [ "$#" -ne 0 ]
then
         echo "\n\n`date +"%d/%m/%Y"` $0: Error en la cantidad de parametros recibida"

         exit 32
fi

EXIT_STAT=''
export EXIT_STAT

if [ -f /tecnol/carga_LN/actulistaneg.sh -a -x /tecnol/carga_LN/actulistaneg.sh ]
then
         /tecnol/carga_LN/actulistaneg.sh
         EXIT_STAT="$?"

         if [ "$EXIT_STAT" -ne 0 ]
         then
                  echo "\n\n$0: LOs errores de cancelacion del prog. /tecnol/carga_LN/actulistaneg.sh, hay que"
                  echo "buscarlos en el sysout del job ACTU_NOVLN"
         fi

else
         echo "\n\n`date +"%d/%m/%Y"` $0: Este programa no existe o no posee permiso de ejecucion"
         exit 31
fi

exit "$EXIT_STAT"
